---

- name: Install wireguard
  apt:
    name: wireguard
    state: latest

- name: Configure interfaces
  template:
    src: netplan_interface
    dest: /etc/netplan/02-wireguard.yaml
    owner: root
    group: root
    mode: 0600
  notify: Netplan reload
